---
apiVersion: v1
kind: Service
metadata:
  name: metrics-api-service
  labels:
    app: metrics-api-service
spec:
  type: NodePort
  selector:
    app: metrics-api-service
  ports:
    - protocol: TCP
      port: 8080
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-api-service
spec:
  selector:
    matchLabels:
      app: metrics-api-service
  replicas: 2
  template:
    metadata:
      labels:
        app: metrics-api-service
    spec:
      containers:
        - name: metrics-api-service
          image: madhawachaminda1984/deviq-metrices-api:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8081





