name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

# permissions:
#  contents: read

jobs:
  deploy:
    name: Deploy to EC2 on master branch push 
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to server 1
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME}}
        TARGET: ${{ secret.TARGET_DIR }}
      

    - name: Execute remote SSH commands using ssh keys
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{secrets.HOST_DNS}}
        key: ${{secrets.EC2_SSH_KEY}}
        scripts: |
            hostname
            pwd
            ls -altr
  
